### ISSUE TITLE
Update README.md by mentioning about proxy configuration

### ISSUE THREAD

**Issue by achaitanyasai** [Tatoeba/imouto#23]
I think it's better if we can mention about proxy configuration in readme.md

**Comment by jiru** [comment]
It seems to me that this problem should be addressed by vagrant that should somehow error when it fails to forward ports. If, in the meantime, you want to update the README.md to warn people about this problem, please explain in detail the problem you had, or better, make a pull request.

**Comment by achaitanyasai** [comment]
I just wanted to modify some thing like this : <br>
Usage Instructions
-----------

###Imouto for development:
- Install the requirements above
- Clone the github repo on your machine:
```bash
$ git clone https://github.com/Tatoeba/imouto.git
```
- Use vagrant to first download the box and then provision it using ansible. Please be patient, it takes a while for vagrant to download the ~300MB box on your machine and then to provision it using ansible.
```bash
$ cd imouto #ignore if already in the imouto directory
```
- Configure proxy on Vagrant VM if you are behind proxy server : 
    - Install proxyconf plugin : 
<pre>
$ vagrant plugin install vagrant-proxyconf
</pre>
    - And then add the following to Vagrantfile :  
<pre>
Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://username:password@proxy_host:proxy_port"
    config.proxy.https    = "http://username:password@proxy_host:proxy_port"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
end
</pre>
```bash
$ vagrant up
```
- Once it completed, you should be able to:
  - Access your local instance of Tatoeba at http://localhost:8080/
  - Run `vagrant ssh` to ssh to the machine.
  - Use the script `mount.sh` (run it to get usage instructions) to mount any of the VM's directory on your host machine in order to modify files without ssh-ing to the VM.

**Comment by liori** [comment]
@jiru: I guess this ticket is a result of our problem-solving on IRC, where achaitanyasai reported that ansible was unable to download package lists (`apt-get update`) before even installing vital packages like `git` because of missing proxy settings. If so, it has nothing to do with port forwarding.

@achaitanyasai: it would be great if you could make it into a pull request; this is the standard form of sending new contributions to Github projects.

**Comment by jiru** [comment]
@liori I see, thank you!

**Comment by achaitanyasai** [comment]
@liori  Yeah I will make a PR, thank you.
