### ISSUE TITLE
Mount / Unmount on MacOS

### ISSUE THREAD

**Issue by Poulpisator** [Tatoeba/imouto#48]
I have experimented on the mount.sh script on MacOS, and that was a little bit tedious. 

Here are my remarks:  
1. readlink is not the same on Mac, so `readlink -f` fails with an illegal option error. I found this page to help me https://github.com/matejak/argbash/issues/74, so I installed coreutils in order to be able to call greadlink:
`brew install coreutils`   
and I replaced `readlink` by `greadlink` in the script. 

2. The script has to be called with `sh` and not run by itself (`. mount.sh`) otherwise `"$0"` becomes `-bash` and the script fails. That might be an obvious one, but being unused to scripts, that wasn't obvious to me :) 

3. After successfully mounting the folder, let's call it _Tatoeba_mounted_, its displayed named in Mac Finder becomes something like _OSXFUSE Volume 0 (sshfs)_. Its name in the Terminal stays _Tatoeba_mounted_.

4. I couldn't unmount using the `mount.sh` script because  
`fusermount: command not found`
I don't why it is so, but maybe I will investigate that later...  
I succeeded to unmount using
`diskutil unmount Tatoeba_mounted`  
Note however that for this command to succeed, nothing should currently make use of the _Tatoeba_mounted_ directory (that includes Terminals currently inside _Tatoeba_mounted_)

**Comment by jiru** [comment]
About 1., I will have to find a replacement.
About 2., the proper way to run the script is `./mount.sh`.
About 3., it looks like we can adjust the volume name with the sshfs option `-o volname=X`; can you try to edit the script to add that option, and see how it looks in Mac Finder?
About 4., can you check if the command `umount Tatoeba_mounted` works too?

**Comment by jiru** [comment]
Andreas solved the readlink problem. What about 3. and 4. in my previous comment?

**Comment by jiru** [comment]
This should no longer be a problem with Tatovm, see 6a295b267e15e298ff65dac6de129886ad91986d.
