### ISSUE TITLE
Lower default memory in Vagrantfile

### ISSUE THREAD

**Issue by trang** [Tatoeba/imouto#50]
https://github.com/Tatoeba/imouto/blob/master/Vagrantfile#L14

`v.memory` is currently set at 2048 MB. Would there be any disadvantage lowering it to 512 MB or maybe even lower?

We should probably mention in the "Requirements" what is the minimum amount of RAM recommended and then set `vm.memory` according to that.

If I'm a new contributor who has a lot of RAM, then this doesn't affect me.
If I'm a new contributor who doesn't have a lot of RAM, then I won't have to worry about changing the Vagrantfile.

**Comment by jiru** [comment]
I agree that it would be better to provide a VM using less RAM by default.

The reason it is set to 2GB is that Manticore, even without any sentences indexed, uses more than 1GB of RAM (an issue that is covered by #51, but I can't see an easy solution for that so far). If you lower the RAM, I think Manticore will just fail to start at boot or fill up swap space.

We can consider not enabling Manticore by default. In that case, we need to add documentation about how to enable Manticore and run a reindexation and the memory requirement implications. It's about weighting the benefits of having a full-featured VM with search functionality vs. lower RAM VM without search.
