### ISSUE TITLE
Limit the number of indexed languages for development

### ISSUE THREAD

**Issue by jiru** [Tatoeba/imouto#51]
The current implementation makes Manticore index all the languages, even the ones without sentences. This unnecessarily bloats RAM requirements of development instances of Tatoeba. Empty indexes use a few MB of RAM, multiplied by the number of languages (currently 330) and multiplied by two (one delta index and one main index).

One possible solution is to prevent Manticore from indexing languages that have no sentences.

**Comment by jiru** [comment]
I have a new idea to limit the resources needed by having a lot of empty indexes. Basically, we can group all the indexes that share the same Manticore configuration into a single index, say `grouped_indexes`. Then, we can ease access to this grouped index using "aliases" like this:

```
index ryu_main_index
{
    type = distributed
    local = grouped_indexes
}
```
The above block allows to query the index `ryu_main_index` just about the same way we query, say, `ota_main_index` (a regular index). Except that `ryu_main_index` will return unwanted languages. To prevent that, we add an extra attribute `lang` in `grouped_indexes` to filter by language. Giving that this `lang` attribute would not exist in `ota_main_index`, we should be able to query them seamlessly using [`EXIST()`](https://docs.manticoresearch.com/latest/singlehtml/index.html#exist), like this:

```
# The lang attribute does exist in ryu, so it filters
select id, EXIST('lang', 'ryu') as lang from ryu_main_index where lang = 'ryu';
# The lang attribute does not exist in ota, so the filter doesn’t do anything
select id, EXIST('lang', 'ota') as lang from ota_main_index where lang = 'ota';
```

However the above doesn’t work because `EXIST()` only works on integers or MVA, not strings, so we need to convert the ISO codes into integers. Since language codes are all lowercase and can be up to 4 characters long, it’s easy to just parse them as simple base-26 numbers, the highest ("zzzz") would be 25^4 = 390625.

Such integer can be stored into a [32-bit attribute](https://docs.manticoresearch.com/latest/singlehtml/index.html#sql-attr-uint). All that should make the grouped index transparent to the PHP side, so that Manticore can group or ungroup as it pleases.

I guess that the amount of RAM required by this new `lang` attribute won’t be worth storing a language in the grouped index when the index becomes too big. This means we better only group languages that are rather small, not just all the languages sharing the same Sphinx configuration. And we need to think about a mechanism to take out a language from the grouped index into its own index. We’d also have to check how the grouped index performs compared to separate indexes.

**Comment by AndiPersti** [comment]
> I have a new idea to limit the resources needed by having a lot of empty indexes. Basically, we can group all the indexes that share the same Manticore configuration into a single index, say `grouped_indexes`. Then, we can ease access to this grouped index using "aliases" like this:

While querying shouldn't be a problem with this approach, reindexing would be a little bit more complicated as I understand it:

> This index only contains references to other local and remote indexes - so it could not be directly reindexed, and you should reindex those indexes which it references instead.
(from https://docs.manticoresearch.com/latest/html/searching/distributed_searching.html#distributed-searching)

So we would need a list of all the languages in the grouped index which is accessible to PHP (a local configuration setting?) and we would need a special language code for the grouped index.

But why not use the solution you described in your initial comment:
> One possible solution is to prevent Manticore from indexing languages that have no sentences.

i.e. check the number of sentences before creating the configuration section for a language (and maybe limit that check to development environments only)?

**Comment by jiru** [comment]
> check the number of sentences before creating the configuration section for a language (and maybe limit that check to development environments only)?

I agree that would be certainly much simpler. :sweat_smile: I wonder what happens when Manticore has no index though.

Also, when searching, we’d have to more gracefully handle the case where an index doesn't exist, otherwise the search error will likely to confuse new developers.

**Comment by jiru** [comment]
A great part of the RAM usage seems to be caused by our complex values for `charset_table` and `ngram_chars`. After simplifying these and rebuilding all indexes, searchd RAM usage drops from 1.6GB to 670MB. Setting them to the aliases `non_cjk` and `cjk` doesn’t help.

Also setting `preopen_indexes = 0` saves about 65MB.
