### ISSUE TITLE
How to import all the database to local  environment?

### ISSUE THREAD

**Issue by antyol** [Tatoeba/imouto#59]
I'm new to vagrant and VM world, i just installed everything locally and got it up and running but i have an empty database. i read some of the yaml config files but didn't know how to use them in order to fetch/download the database locally.

I've read all the readme files but didn't get anywhere.

Any help or guidance will be much appreciated, thanks.

**Comment by AndiPersti** [comment]
There currently is no script for importing the data from the production site. See https://github.com/Tatoeba/tatoeba2/issues/2010

But for the start you do not really need it. Just add some items you need (sentences, comments, wall posts, ...) for testing.

**Comment by jiru** [comment]
Closing this issue as a duplicate of Tatoeba/tatoeba2#2010.
