### ISSUE TITLE
Problems on Manticore?

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/imouto#61]
I tried to limit which languages Manticore indexes. I run  ```cake sphinx_conf por eng fra esp deu ell ita | sudo tee /etc/manticoresearch/manticore.conf``` as described [here](https://github.com/Tatoeba/imouto/blob/master/README.md#limiting-the-number-of-indexed-languages) and I got this:

![image](https://user-images.githubusercontent.com/7658430/81113373-7f79a900-8ef6-11ea-926b-1821d75903a9.png)

**Comment by Yorwba** [comment]
The error you're getting says that the commands `cake` and `sudo` are not available on your computer. That's because you're trying to run them under MINGW, where you probably have neither CakePHP nor Manticore installed. The command will only work inside the vagrant box.

**Comment by RyckRichards** [comment]
I see. It's my first try ever hehe

I tried to run on the Command Prompt both cake and sudo and I got this:

![image](https://user-images.githubusercontent.com/7658430/81120954-19941e00-8f04-11ea-9ff8-d66e3b617300.png)

After that, I tried to run cake only. 

![image](https://user-images.githubusercontent.com/7658430/81121044-434d4500-8f04-11ea-99a5-36b9864656ac.png)

**Comment by AndiPersti** [comment]
As Yorwba said, this commands only work inside the VM. But according to #60 you are not able to start the VM yet, are you?

**Comment by RyckRichards** [comment]
Uhm... I haven't noticed that... sorry :/  I started VM and so I did ```vagrant up```. I got this:

![image](https://user-images.githubusercontent.com/7658430/81152519-643f8580-8f58-11ea-874e-d33994a0c5ee.png)

**Comment by trang** [comment]
I'm closing this.

As we've discussed @RyckRichards, you won't be able to get the VM to work and with your current Tatoeba installation, the search engine (and other features) won't be available.

If you were able to start the VM with `vagrant up`, you would have had to connect to the VM with `vagrant ssh` and the `cake...` command could be executed from there.
