### ISSUE TITLE
Unable to download Tatoeba VM.

### ISSUE THREAD

**Issue by mimzivvimzi** [Tatoeba/imouto#63]
Hi everyone,

Could someone please help me address this issue?  After typing "vagrant up" it started to download, but at the very end, I received this error:

`There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["startvm", "4e7ba106-63fc-4d6d-bd80-30d2461c3537", "--type", "headless"]
Stderr: VBoxManage: error: The virtual machine 'imouto_default_1590053227522_18404' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine`

My operating system is macOS Catalina 10.15.4.

-M

**Comment by AndiPersti** [comment]
Can you show us the log file for VirtualBox (`$HOME/VirtualBox VMs/imouto_default_1590053227522_18404/Logs/VBox.log`)?

**Comment by mimzivvimzi** [comment]
I don't have a Logs folder.  This is what was in the imouto_default_1590053227522_18404 folder:

`imouto_default_1590053227522_18404.vbox
imouto_default_1590053227522_18404.vbox-prev`

**Comment by AndiPersti** [comment]
Can you start the VirtualBox GUI?
Do you see the VM listed and can you start it from the GUI? Or do you get the same error?
Can you start other VMs?

**Comment by mimzivvimzi** [comment]
Hi,

I can see it, but when I press "start" I have this error:

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | MachineWrap
Interface: | IMachine {85632c68-b5bb-4316-a900-5eb28d3413df}

Thanks,
Michelle

**Comment by AndiPersti** [comment]
Were there any problems when you've installed VirtualBox?

I did some researching and found some links that point to a problem with the security settings:
- https://www.vagrantup.com/docs/other/macos-catalina.html
- https://github.com/hashicorp/vagrant/issues/10314
- https://www.unixcloudfusion.in/2018/10/solved-stderr-vboxmanage-error-virtual.html

**Comment by AndiPersti** [comment]
I forgot to mention that there should be a log file for the VirtualBox service process (VBoxSVC) in `$HOME/Library/VirtualBox` which may contain more information about the error.

**Comment by mimzivvimzi** [comment]
These files were in there.

VBoxSVC.log			compreg.dat
VBoxSVC.log.1			selectorwindow.log
VBoxSVC.log.2			selectorwindow.log.1
VBoxSVC.log.3			selectorwindow.log.2
VBoxSVC.log.4			selectorwindow.log.3
VBoxSVC.log.5			selectorwindow.log.4
VBoxSVC.log.6			vbox-ssl-cacertificate.crt
VirtualBox.xml			xpti.dat
VirtualBox.xml-prev

**Comment by mimzivvimzi** [comment]
No, I don't remember there being any problems with it.  I did accidentally download Vagrant twice because I didn't know that it wouldn't show up in my Applications.  Not sure if that would cause any problems.

**Comment by AndiPersti** [comment]
> These files were in there.
> 
> VBoxSVC.log
> VBoxSVC.log.1

Can you post the contents of these two files? (Maybe create a gist.)

**Comment by mimzivvimzi** [comment]
I've never created a gist before but should I make it public and then will I be able to send it to you?  I tried to find/replace my name with a placeholder wherever it was referred to.  Not sure if there's anything else that's potentially sensitive.

**Comment by AndiPersti** [comment]
You can create a secret gist and then send me the URL via a Tatoeba private message (my username there is `rumpelstilzchen`).

**Comment by mimzivvimzi** [comment]
Ok, I sent you a Tatoeba private message.  Thanks!

**Comment by AndiPersti** [comment]
@jiru This issue can be closed. It was resolved by reinstalling VirtualBox and Vagrant.
