### ISSUE TITLE
mount Tatoeba/ => wrong fs type, bad option, bad superblock

### ISSUE THREAD

**Issue by blackslate** [Tatoeba/imouto#65]
I'm working on Ubuntu 16.04 and following the instructions to set up Tatoeba locally, as described [here](https://github.com/Tatoeba/imouto/blob/master/README.md#imouto-for-development)

I've got vagrant and virtualbox running. 
 
I successfully get as far as the section on [Accessing the source code](https://github.com/Tatoeba/imouto/blob/master/README.md#using-nfs-unixmacos), but here I run into an error.
 
Here are the two lines I added to /etc/fstab:
```
 
# Change /your/path/to/imouto/Tatoeba/ to the actual path of Imouto
localhost:/home/vagrant/Tatoeba /home/blackslate/Repos/imouto/Tatoeba nfs noauto,user,exec,port=8049,soft,timeo=10
```
 
However, now when I run either `mount Tatoeba/`` or vagrant up`, I get this message:
 
```
mount Tatoeba/
mount: wrong fs type, bad option, bad superblock on localhost:/home/vagrant/Tatoeba,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
 
       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```
A folder named Tatoeba appears in the Ubuntu Toolbar and in my Bookmarks, but clicking on it either fails silently or displays the same error in an alert.

**Comment by AndiPersti** [comment]
Do you have the package `nfs-common` installed? (see https://help.ubuntu.com/community/SettingUpNFSHowTo#NFSv4_client)

What is the output of `dmesg | tail` (immediately after the failed attempt)?

**Comment by l-bdx** [comment]
I had the same problem.  Installing the nfs-common package solved it. Thanks!

**Comment by blackslate** [comment]
I ran the command `sudo apt-get install nfs-common` and now everything is working fine. Thanks for your help!
