### ISSUE TITLE
Generating exports as described in README fails

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/imouto#69]
Steps to reproduce:
1. Create a new VM and log into it
2. From the code root directory run the command for generating the exports: 
````
vagrant@stretch:~$ cd Tatoeba && sudo ./docs/cron/runner.sh ./docs/cron/export.sh
sudo: ./docs/cron/runner.sh: command not found
````
Problem 1: `runner.sh` isn't executable.

Fixing this and rerunning the command produces:
````
vagrant@stretch:~/Tatoeba$ chmod 744 ./docs/cron/runner.sh
vagrant@stretch:~/Tatoeba$ sudo ./docs/cron/runner.sh ./docs/cron/export.sh
PHP Warning:  require(/var/www-prod/config/paths.php): failed to open stream: No such file or directory in Command line code on line 1
PHP Fatal error:  require(): Failed opening required '/var/www-prod/config/paths.php' (include_path='.:/usr/share/php') in Command line code on line 1
PHP Warning:  require(/var/www-prod/config/paths.php): failed to open stream: No such file or directory in Command line code on line 1
PHP Fatal error:  require(): Failed opening required '/var/www-prod/config/paths.php' (include_path='.:/usr/share/php') in Command line code on line 1
PHP Warning:  require(/var/www-prod/config/paths.php): failed to open stream: No such file or directory in Command line code on line 1
PHP Fatal error:  require(): Failed opening required '/var/www-prod/config/paths.php' (include_path='.:/usr/share/php') in Command line code on line 1
./docs/cron/runner.sh: line 10: ./docs/cron/export.sh: Permission denied
````
Problem 2: The path for the code root directory is hardcoded (`/var/www-prod/`) to the value used on the production server and so the script needs to be modified manually in all other environments (even the dev server uses another code root directory).

The only solution which I can think of at the moment is to have a configuration file at a standard path where the code root directory is stored at installation time of the server/VM. (e.g. `/etc/tatoeba.conf`).
Any other ideas?

(There are other places where that path is hardcoded but I think most of them are unused/obsolete:
````
vagrant@stretch:~/Tatoeba$ grep -rlF 'var/www-prod' .
./docs/database/scripts/add_lang.sh
./docs/nginx/default-alt
./docs/nginx/default
./docs/nginx/default-static
./docs/nginx/default-static-alt
./docs/nginx/default-prod
./docs/cron/backup.sh
./docs/cron/merge_indexes.sh
./docs/cron/export_wwwjdic.sh
./docs/cron/export.sh
./docs/cron/refresh_index.sh
./docs/cron/refresh_delta.sh
./docs/cron/runner.sh
````
)

**Comment by jiru** [comment]
Thanks for wrapping it up.

We do use some of the cron scripts, especially:
```
./docs/cron/merge_indexes.sh
./docs/cron/export.sh
./docs/cron/refresh_delta.sh
./docs/cron/runner.sh
```

You can also check the crontab on the server.

> The only solution which I can think of at the moment is to have a configuration file at a standard path where the code root directory is stored at installation time of the server/VM. (e.g. `/etc/tatoeba.conf`).
> Any other ideas?

We would have to hardcode the path in nginx configuration anyway.

I’d rather get rid of these scripts entirely in favour of using the `cake` command only and make it available in the PATH. We already do this in Imouto using the file `/etc/profile.d/custom-path.sh`.

Among the scripts we actually use, only `export.sh` is a real shell script; the others are just wrappers to the cake command. We could do the opposite: use a PHP wrapper for `export.sh`.

**Comment by AndiPersti** [comment]
> We would have to hardcode the path in nginx configuration anyway.

Yes, so I better short-term fix would be to create a symlink (like we do already on the dev server).

> I’d rather get rid of these scripts entirely in favour of using the `cake` command only and make it available in the PATH. We already do this in Imouto using the file `/etc/profile.d/custom-path.sh`.

I agree that this would be the preferred solution.

**Comment by jiru** [comment]
Closing this issue because the instructions in the README file work now and I am closing this repository.
