### ISSUE TITLE
File permissions errors

### ISSUE THREAD

**Issue by AndiPersti** [Tatoeba/imouto#71]
After creating a new VM (version 0.0.8) and running the tests (`phpunit`) I get errors like:
```
Warning Error: SplFileInfo::openFile(/home/vagrant/Tatoeba/tmp/cache/myapp_cake_routes_route_collection): failed to open stream: Permission denied in [/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 406]
```

The problem is that both `vagrant` and `www-data` access the `tmp` and `logs` directories and only the first touching a file will be able to modify it later.

Similar when I run the command to update the indexes (e.g. `sudo bin/cake sphinx_indexes update main eng`):
```
Warning Error: SplFileInfo::openFile(/home/vagrant/Tatoeba/tmp/cache/persistent/myapp_cake_core_translations_languages_en__u_s): failed to open stream: Permission denied in [/home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Cache/Engine/FileEngine.php, line 406]

PHP Warning:  file_put_contents(/home/vagrant/Tatoeba/logs/cli-error.log): failed to open stream: Permission denied in /home/vagrant/Tatoeba/vendor/cakephp/cakephp/src/Log/Engine/FileLog.php on line 133
```
Here the user `manticore` cannot access the cached translations and then tries to log the warning error, i.e. it also needs to have access to files inside `tmp` and `logs`.

I get the same warnings on the prod server if I run the index updating shell manually but for the cron job we use a wrapper script which hides the warnings.

On the dev server, the script for updating the translations will remove the cached translation files every 10 minutes so the sphinx shell can create new files as long as no other process touches the file. This is unlikely because it uses the `en_US` locale which is only used by other command line processes. But if I remove the files and create them as another user (e.g. `sudo -u www-data touch tmp/cache/persistent/myapp_cake_core_translations_{default,languages}_en__u_s`)  I also get the warnings on the dev server.

One solution would be to create a new group (e.g. `tatoeba`), set the group owner for `tmp` and `logs` to that group (and also set SGID on that directories) and add the group to all the users that need to access these directories (`vagrant`, `www-data` and `manticore`).
We would also need to set the gid in the sphinx_indexes shell in addition to setting the uid.

Another possibility is to make `tmp` and `logs` read-/writeable for anyone.

**Comment by jiru** [comment]
Your suggested solution sounds good.

Note that this is not supposed to be a problem on Imouto because of Tatoeba/tatoeba2@5bf8b84703cf2af00cfc47e7d37b7894b907f362. I wonder why you are getting the errors. Anyway, that commit is not really solving the problem and should probably be reverted if we implement your solution.

**Comment by jiru** [comment]
That said, I’d rather not have the cake command generate any cache file in the first place. It doesn’t really make sense to me. There must be a way to tweak the behaviour of the cake console using `config/bootstrap_cli.php`.

**Comment by jiru** [comment]
As for the log files, it looks like it’s also possible to provide a `mask` option in the configuration.

**Comment by AndiPersti** [comment]
> Note that this is not supposed to be a problem on Imouto because of [Tatoeba/tatoeba2@5bf8b84](https://github.com/Tatoeba/tatoeba2/commit/5bf8b84703cf2af00cfc47e7d37b7894b907f362). I wonder why you are getting the errors.

The mask only applies when the user is actually allowed to create a file. Both `logs` and `tmp` are setup so that only the owner and the group have write access:
```
vagrant@buster:~/Tatoeba$ ls -ld tmp/ logs/
drwxrwxr-x 2 vagrant www-data 4096 Jul  9 18:39 logs/
drwxrwxr-x 3 vagrant www-data 4096 Jun 13 09:14 tmp/
vagrant@buster:~/Tatoeba$ touch logs/vagrant
vagrant@buster:~/Tatoeba$ sudo -u www-data touch logs/www-data
vagrant@buster:~/Tatoeba$ sudo -u manticore touch logs/manticore
touch: cannot touch 'logs/manticore': Permission denied
```
The cache files don't exist that's why I get the errors.
And the log file `cli-error.log` has only write access for the owner:
```
vagrant@buster:~/Tatoeba$ ls -l logs/cli-error.log
-rw-r--r-- 1 vagrant vagrant 4572 Jun 13 10:33 logs/cli-error.log
```

**Comment by AndiPersti** [comment]
> That said, I’d rather not have the cake command generate any cache file in the first place. It doesn’t really make sense to me. There must be a way to tweak the behaviour of the cake console using `config/bootstrap_cli.php`.

There is [`Cache::disable()`](https://book.cakephp.org/3/en/core-libraries/caching.html#Cake\Cache\Cache::disable). Appending it to the end of `config/bootstrap_cli.php` avoids the errors. But this was just a quick test.

**Comment by jiru** [comment]
Alternatively, we could use the [Array cache engine](https://api.cakephp.org/3.8/class-Cake.Cache.Engine.ArrayEngine.html) in `bootstrap_cli.php`:

> While not useful in production settings this engine can be useful in tests or console tools where you don't want the overhead of interacting with a cache servers, but want the work saving properties a cache provides.

As for the manticore user, maybe we can make it so that we only switch UID to execute the indexer and not during the rest of the PHP code.
